### ISSUE TITLE
只能用音量键翻页，没有做滑动翻页么？

### ISSUE THREAD

**Issue by fuyifang** [CodingBingo/FastReader#1]

**Comment by CodingBingo** [comment]
这个会在下一个版本加上去，目前下一个版本暂定这个周末提上去。

**Comment by hanshuo11** [comment]
麻烦问一下，源码下载后怎么运行？

**Comment by Alexzhang369** [comment]
你好 CodingBingo ，我下载了你的代码 并做了修改，开发了新的功能，作为测试。你的代码不错。

**Comment by CodingBingo** [comment]
目前点击翻页已经添加

**Comment by Alexzhang369** [comment]
greendao怎么对TXT 进行分章节呢

**Comment by CodingBingo** [comment]
并不是用greendao对txt文件分章节的，详细请看代码哈。

**Comment by CodingBingo** [comment]
并不是用greendao对txt文件分章节的，详细请看代码哈。 @Alexzhang369
